FROM ubuntu:14.04
MAINTAINER Siem Hermans, <siem.hermans@os3.nl>
LABEL version="1.0"
LABEL role="Performance measurement"

# Set correct directory
ENV dir /root
WORKDIR ${dir}

# Update sources & install essential tools  
RUN apt-get -qq update && apt-get install -yqq \
  wget \
  build-essential \
  git \
  iperf

# Pull and build testing tools (iperf & netperf)
RUN wget --no-check-certificate https://iperf.fr/download/iperf_3.0/iperf3_3.0.11-1_amd64.deb https://iperf.fr/download/iperf_3.0/libiperf0_3.0.11-1_amd64.deb
RUN dpkg -i libiperf0_3.0.11-1_amd64.deb iperf3_3.0.11-1_amd64.deb && rm libiperf0_3.0.11-1_amd64.deb iperf3_3.0.11-1_amd64.deb
RUN wget --no-check-certificate ftp://ftp.netperf.org/netperf/netperf-2.7.0.tar.gz && tar -xzvf netperf-2.7.0.tar.gz
RUN cd netperf-2.7.0 && ./configure --enable-demo=yes && make && make install && rm ../netperf-2.7.0.tar.gz

# Install binaries and clean up directories
RUN mv -t /usr/bin netperf-2.7.0/src/netperf netperf-2.7.0/src/netserver && rm -rf netperf-2.7.0/

# Include netperf and iperf scripts
ADD scripts/serv_setup.sh ${dir}/server.sh
RUN chmod +x server.sh

# Execute performance measurements
ENTRYPOINT ["./server.sh"]
STOPSIGNAL SIGKILL

# Expose the default ports, statically linked (iperf, iperf3, netperf)
EXPOSE 5001:5001 5201:5201 12865:12865
